name: flutter_feed_engine
description: "Instagram-style image/video feed with advanced caching and prefetch."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.0
  equatable: ^2.0.0

  # Dependency Injection
  get_it: ^8.0.0

  # Image Cache
  cached_network_image: ^3.4.0
  flutter_cache_manager: ^3.4.0

  # Video
  video_player: ^2.9.0

  # Local Database
  drift: ^2.22.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.9.0

  # Network / Connectivity
  connectivity_plus: ^6.1.0

  # UI
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2

  # Utils
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  drift_dev: ^2.22.0
  bloc_test: ^9.1.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
